services:
  - type: web
    name: personal-expense-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn expense_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: expense_project.settings
      - key: PYTHON_VERSION
        value: 3.11.9
